bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "/home/matt/Desktop/luna/src/astro_launch/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/home/matt/Desktop/luna/src/astro_launch/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "/home/matt/Desktop/luna/src/astro_launch/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "base_link"
    transform_tolerance: 0.5

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 0.25
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 1.0
      downsample_costmap: false
      angle_quantization_bins: 72
      analytic_expansion_max_length: 3.0
      minimum_turning_radius: 1.2
      motion_model_for_search: "REEDS_SHEPP"
      allow_backwards: true
      reverse_penalty: 1.1
      change_penalty: 0.0
      non_straight_penalty: 1.0
      allow_unknown: false
      allow_reverse: true




global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 2.0
      footprint_clearing_enabled: true
      use_sim_time: false
      robot_base_frame: "base_link"
      global_frame: "map"
      robot_radius: 0.75 
      footprint: "[[0.69, 0.37], [0.69, -0.37], [-0.69, -0.37], [-0.69, 0.37]]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        map_subscribe_transient_local: True
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_topic: "/map"
        subscribe_to_updates: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        footprint_clearing_enabled: false
        max_obstacle_height: 0.5
        combination_method: 1
        observation_persistence: 0.0
        scan:
          sensor_frame: "camera_link"
          topic: /grid_cloud
          max_obstacle_height: 0.5
          clearing: true
          marking: true
          data_type: "PointCloud2"
          raytrace_max_range: 2.5  # how far to clear free space
          raytrace_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.4

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 5.0
    use_velocity_scaled_lookahead_dist: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      use_rotate_to_heading: false
      desired_linear_vel: 0.5
      max_linear_accel: 1.5
      min_lookahead_dist: 0.3
      lookahead_dist: 0.8
      lookahead_time: 1.2
      min_linear_vel: -0.2
      allow_backwards: true
      transform_tolerance: 0.3
      use_rotate_to_heading: false
      max_angular_accel: 0.3
      use_interpolation: true
      allow_reversing: true



local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 5.0
      use_sim_time: false
      robot_base_frame: "base_link"
      global_frame: "odom"
      rolling_window: true


lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - map_server
      - controller_server
      - planner_server
      - bt_navigator
      - behavior_server
